name: 'Master Code Updated'
on: push

jobs:
  build:
    name: 'Generate dist'
    runs-on: ubuntu-latest

      - name: Create a new release
        uses: Xotl/cool-github-releases@v1
        with:
          mode: update
          tag_name: ${{env.NEW_TAG}}
          github_token: ${{ github.token }} 
