name: 'Master Code Updated'
on: push

commit:
    name: 'Commit new dist & version files'
    #needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Create a new release
        uses: Xotl/cool-github-releases@v1
        with:
          mode: update
          tag_name: ${{env.NEW_TAG}}
          github_token: ${{ github.token }} 
